#!/usr/bin/python3

character_dict = {
      "Stats": {
          "strength":{
              "base":0,
              "mod":0,
              "save":0
          },
          "dexterity":{ 
              "base":0,
              "mod":0,
              "save":0
          },
          "constitution":{
              "base": 0,
              "mod":0,
              "save":0
          },
          "intelligence":{
              "base": 0,
              "mod":0,
              "save":0
          },
          "wisdom" :{
               "base": 0,
               "mod":0,
               "save":0
          },
          "charisma" :{
               "base": 0,
               "mod":0,
               "save":0
      },
   },
# If a stat is in this dict, add proficiency modifier to the saving throw.
# Otherwise, the saving throw is just the modifier
    "saving_throws":{
    },
    "initiative":0,
    "Languages":{
        "common":"Common"
    },
    "name":'',
    "total_level":0,
# The available spell slots is dependent on the caster level.
    "caster_level":0,
# For Artificers, Paladins, and Rangers
    "half_caster_level":0,
# For Arcane Trickster Rogues and Eldritch Knights
    "semi_caster_level":0,
    "spell_slots":{
        "first":0,
        "second":0,
        "third":0,
        "fourth":0,
        "fifth":0,
        "sixth":0,
        "seventh":0,
        "eighth":0,
        "ninth":0
    },
    "pact_magic":{
        "first":0,
        "second":0,
        "third":0,
        "fourth":0,
        "fifth":0,
    },
# The initial class for multiclassing purposes
    "initial_class":'',
    "player_class":{
        "artificer":{
            "class_level":0,
            "subclass":''
        },
        "barbarian":{
            "class_level":0,
            "subclass":''
        },
        "bard":{
            "class_level":0,
            "subclass":''
        },
        "cleric":{
            "class_level":0,
            "subclass":''
        },
        "druid":{
            "class_level":0,
            "subclass":''
        },
        "fighter":{
            "class_level":0,
            "subclass":''
        },
        "monk":{
            "class_level":0,
            "subclass":''
        },
        "paladin":{
            "class_level":0,
            "subclass":''
        },
        "ranger":{
            "class_level":0,
            "subclass":''
        },
        "rogue":{
            "class_level":0,
            "subclass":''
        },
        "sorcerer":{
            "class_level":0,
            "subclass":''
        },
        "warlock":{
            "class_level":0,
            "subclass":'',
            "pact":''
        },
        "wizard":{
            "class_level":0,
            "subclass":''
        },
    },
    "Tools":{
    },
    "tool_expertise":{
    },
    "dragonmark":{
    },
# Used to confirm the boon from aberrant dragonmark was used
    "aberrant_check":'',
    "boon":{
    },
# Modifiers for spell attacks and saving throws
    "spell_modifier":{
        "constitution":{
            "attack": 0,
            "save":0
        },
        "intelligence":{
            "attack": 0,
            "save":0
        },
        "wisdom":{
            "attack":0,
            "save":0
        },
        "ki_save":0,
        "charisma":{
            "attack":0,
            "save":0
        },
    },
    "speed":0,
# Used for when monks and barbarians get unarmored movement whether or not they have heavy or any armor respectively.
    "unarmored_movement_barbarian":0,
    "unarmored_movement_monk":0,
# In case a race is added that has a climbing, swimming, or flying speed
    "climb_speed":0,
    "swim_speed":0,
    "fly_speed":0,
    "size":'',
    "Kits":{
    },
    "hp":0,
# Hit Dice
    "d6":0,
    "d8":0,
    "d10":0,
    "d12":0,
    "Vehicles":{
    },
    "race":'',
    "background":'',
    "Instruments":{
    },
    "Gaming_Set":{
    },
#Weapon Proficiencies
    "Weapon_Prof":{
    },
#Armor Proficiencies
    "Armor_Prof":{
    },
# Armor available to equip
    "chest_equip_armor":{
    },
    "shield_equip_armor":{
    },
    "boots_equip_armor":{
    },
    "bracers_equip_armor":{
    },
    "magical_items":{
    },
    "attuned_items":{
    },
    "weapons":{
    },
# Equipped armor
    "chest_armor":'',
    "shield":'',
    "boots":'',
    "bracers":'',
    "armor_class":0,
    "base_armor_class":0,
    "natural_armor_class":0,
    "monk_armor_class":0,
    "barbarian_armor_class":0,
    "sorcerer_armor_class":0,
    "passive_perception":0,
    "sorcery_points":0,
    "martial_arts":'',
    "ki_points":0,
    "ki_save":0,
    "rage":0,
    "rage_damage":0,
    "sneak_attack": 0,
    "inspiration_die":'',
# Used for regular metamagic
    "metamagic":{
    },
# Used for Metamagic Adept feat
    "metamagic_adept":{
    },
    "elemental_disciplines":{
    },
    "invocations":{
    },
    "pact_invocations":{
    },
# Used for Beguiling Influence. If the player does not already have proficiency in those skills, add them here as well. If the player removes the invocation, remove the skill from here and the skill_prof dictionary.
    "influence":{
    },
    "infusions":{
    },
# Battle Master Manuevers
    'maneuvers':{
        "types":{
        },
# The type of die used
        "die": '',
        "number":0,
# The number of d6 dice gained through fighting styles and features
        "d6":0
    },
# Fighting Styles
    "fighter_fighting_styles":{
    },
    "ranger_fighting_styles":{
    },
    "paladin_fighting_styles":{
    },
    "special_fighting_styles":{
    },
#Spells Known
    "spells":{
        "cantrips":{
        },
        "first":{
        },
        "second":{
        },
        "third":{
        },
        "fourth":{
        },
        "fifth":{
        },
        "sixth":{
        },
        "seventh":{
        },
        "eighth":{
        },
        "ninth":{
        }
    },
# Used for spells that are always prepared/can't be switched out
    "special_spells":{
        "cantrips":{
        },
        "first":{
        },
        "second":{
        },
        "third":{
        },
        "fourth":{
        },
        "fifth":{
        },
        "sixth":{
        },
        "seventh":{
        },
        "eighth":{
        },
        "ninth":{
        },
        'racial_spells':{
        },
# Used for cantrips gained through fighting styles
        "fighting_cleric":{
        },
        "fighting_druid":{
        },
        "tome_cantrips":{
        },
        "tome_ritual":{
        }
    },
# Used for when the player wants to switch spells out
# Cantrip dictionaries are used for classes who can swap spells out
    "class_spells":{
        "artificer":{
            "artificer_cantrips":{
            },
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            }
        },
        "bard":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            },
            "sixth":{
            },
            "seventh":{
            },
            "eighth":{
            },
            "ninth":{
            }
        },
# I added the nested leveled dicts later, so I'm just leaving the cantrip dicts as they are
        "bard_cantrips":{
        },
        "cleric":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            },
            "sixth":{
            },
            "seventh":{
            },
            "eighth":{
            },
            "ninth":{
            }
        },
        "cleric_cantrips":{
        },
        "druid":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            },
            "sixth":{
            },
            "seventh":{
            },
            "eighth":{
            },
            "ninth":{
            }
        },
        "druid_cantrips":{
        },
        "fighter":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            }
        },
        "fighter_cantrips":{
        },
# Used for when the fighter gets any spell at levels 8, 14, and 20.
        "fighter_special":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            }
        },
        "paladin":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            }
        },
        "ranger":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            }
        },
        "rogue":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            }
        },
        "rogue_cantrips":{
        },
        "rogue_special":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            }
        },
        "sorcerer":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            },
            "sixth":{
            },
            "seventh":{
            },
            "eighth":{
            },
            "ninth":{
            }
        },
        "sorcerer_cantrips":{
        },
        "warlock":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            },
            "sixth":{
            },
            "seventh":{
            },
            "eighth":{
            },
            "ninth":{
            },
            "sixth_level_arcanum":{
            },
            "seventh_level_arcanum":{
            },
            "eighth_level_arcanum":{
            },
            "ninth_level_arcanum":{
            }
        },
        "warlock_cantrips":{
        },
        "wizard":{
            "first":{
            },
            "second":{
            },
            "third":{
            },
            "fourth":{
            },
            "fifth":{
            },
            "sixth":{
            },
            "seventh":{
            },
            "eighth":{
            },
            "ninth":{
            }
        },
        "wizard_cantrips":{
        },
    },
    "gold":0,
    "Equipment":{
    },
#Misc items given in backgrounds
    "Misc":{
    },
    'favored_enemies':{
    },
    'favored_terrain':{
    },
# Used for Feats
    "feats":{
    },
    "racial_features":{
    },
    "features":{
    },
    "prof_bonus":0,
# Put the name of the skill in this list to give proficiency to that skill
    "skill_prof":{
    },
    "expertise":{
    },
    "acrobatics":0,
    "animal_handling":0,
    "arcana":0,
    "athletics":0,
    "deception":0,
    "history":0,
    "insight":0,
    "intimidation":0,
    "investigation":0,
    "medicine":0,
    "nature":0,
    "perception":0,
    "performance":0,
    "persuasion":0,
    "religion":0,
    "sleight_of_hand":0,
    "stealth":0,
    "survival":0
}
